In [2]:
import numpy as np

In [1]:
# Grid size
N = 4

gamma = 1.0  # No discounting
theta = 1e-4  # Convergence threshold
rewards = -1  # Reward per move

In [5]:
# Initialize value function
V = np.zeros((N, N))
print(V)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
# Define possible actions (up, down, left, right)
actions = [(-1, 0), (1, 0), (0, -1), (0, 1)]

In [7]:
# Value iteration
while True:
    delta = 0  # Track max change in values
    V_new = np.copy(V)
    
    for i in range(N):
        for j in range(N):
            if (i, j) == (N-1, N-1):  # Skip terminal state
                continue
            
            value = 0
            for action in actions:
                ni, nj = i + action[0], j + action[1]
                
                # Stay in place if hitting boundary
                if ni < 0 or ni >= N or nj < 0 or nj >= N:
                    ni, nj = i, j  
                
                value += 0.25 * (rewards + gamma * V[ni, nj])  # Equal probability
                
            V_new[i, j] = value
            delta = max(delta, abs(V_new[i, j] - V[i, j]))
    
    V = V_new
    if delta < theta:
        break


In [8]:
# Print final value function
print(np.round(V, 5))

[[-59.42368 -57.42387 -54.28131 -51.71013]
 [-57.42387 -54.56699 -49.71029 -45.13927]
 [-54.28131 -49.71029 -40.85392 -29.99767]
 [-51.71013 -45.13927 -29.99767   0.     ]]
